import type { Metadata } from "next"
import { Onest } from "next/font/google"
import "./globals.css"
import { SiteSidebar } from "@/components/site-sidebar"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { Sky } from "@/components/scenes/sky"
import { ThemeProvider } from "@/components/theme-provider"
import type React from "react" // Import React

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${onest.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <SidebarProvider>
            <div className="fixed inset-0 -z-10 bg-gradient-to-br from-[#0069AA] to-[#aedaff] dark:from-[#001F33] dark:to-[#003366]">
              <Sky />
            </div>
            <SiteSidebar />
            <SidebarTrigger className="dark:text-white text-black visible md:invisible p-4" />
            <div className="relative z-20">{children}</div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}

